version: "3.9"

services:
  scraper:
    container_name: scraper
    build:
      context: ./
    volumes:
      - ./scraper_volume:/home/scraper
    env_file: .env
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
